-- Migration: Add isRemote column to logs table
--
-- NOTE: This migration is intentionally a no-op. The isRemote column is already
-- created in migrations/001_initial.sql, so this file exists only for history
-- (older deployments applied it against a pre-isRemote schema). Keeping it a
-- no-op makes `wrangler d1 migrations apply` replayable on a fresh database.